// <auto-generated/>
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;


[assembly: AssemblyTitle("GeoCoordinatePortable")]
[assembly:
    AssemblyDescription(
        "GeoCoordinate is a Portable Class Library compatible implementation of System.Device.Location.GeoCoordinate. It is an exact 1:1 API compliant implementation and will be supported until MSFT sees it fit to embed the type. Which at that point this implementation will cease development/support and you will be able to simply remove this package and everything will still work."
        )]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("https://ghuntley.com/")]
[assembly: AssemblyProduct("GeoCoordinate")]
[assembly: AssemblyCopyright("Copyright © Geoffrey Huntley <ghuntley@ghuntley.com> 2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.11.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
